# Generated by Django 4.2.1 on 2023-10-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_options_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('set_publish_status', 'Can publish'), ('change_description', 'change description'), ('change_category', 'change category')], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
