# Generated by Django 4.2.1 on 2023-10-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('publish_status', 'Can publish'), ('change_description', 'change description'), ('change_category', 'change category')], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
